package com.gymflow.domain

/**
 * Typed enum of all error codes returned by GlobalExceptionHandler.
 * Every code in this enum must match exactly the string used in the API contract
 * and the frontend error-code mapping (useAuth.ts, planErrors.ts, membershipErrors.ts).
 */
enum class ErrorCode {
    // Auth
    VALIDATION_ERROR,
    EMAIL_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    REFRESH_TOKEN_INVALID,
    REFRESH_TOKEN_EXPIRED,
    UNAUTHORIZED,

    // Access control
    ACCESS_DENIED,

    // Membership plans
    PLAN_NOT_FOUND,
    PLAN_ALREADY_INACTIVE,
    PLAN_ALREADY_ACTIVE,
    PLAN_HAS_ACTIVE_SUBSCRIBERS,
    PLAN_NOT_AVAILABLE,
    PLAN_EDIT_CONFLICT,
    INVALID_PRICE,
    INVALID_DURATION,
    INVALID_NAME,
    INVALID_DESCRIPTION,
    INVALID_PLAN_ID,
    INVALID_STATUS_FILTER,

    // User memberships
    MEMBERSHIP_ALREADY_ACTIVE,
    NO_ACTIVE_MEMBERSHIP,
    MEMBERSHIP_NOT_FOUND,
    MEMBERSHIP_NOT_ACTIVE,

    // Bookings
    INVALID_CLASS_ID,
    INVALID_USER_ID,
    INVALID_BOOKING_STATUS,
    CLASS_NOT_FOUND,
    CLASS_NOT_BOOKABLE,
    CLASS_ALREADY_STARTED,
    CLASS_FULL,
    CLASS_HAS_ACTIVE_BOOKINGS,
    ALREADY_BOOKED,
    BOOKING_NOT_FOUND,
    BOOKING_NOT_ACTIVE,
    CANCELLATION_WINDOW_CLOSED,
    CAPACITY_BELOW_CONFIRMED_BOOKINGS,

    // Users
    USER_NOT_FOUND,
    READ_ONLY_FIELD,
    INVALID_FIRST_NAME,
    INVALID_LAST_NAME,
    INVALID_PHONE,
    INVALID_DATE_OF_BIRTH,
    INVALID_FITNESS_GOALS,
    INVALID_PREFERRED_CLASS_TYPES,
    INVALID_EMERGENCY_CONTACT,
    INVALID_BIO_FORMAT,

    // Trainers
    TRAINER_NOT_FOUND,
    TRAINER_EMAIL_CONFLICT,
    TRAINER_HAS_ASSIGNMENTS,
    TRAINER_SCHEDULE_CONFLICT,
    ALREADY_FAVORITED,
    FAVORITE_NOT_FOUND,
    INVALID_SORT_FIELD,

    // Rooms
    ROOM_NOT_FOUND,
    ROOM_NAME_CONFLICT,
    ROOM_HAS_INSTANCES,

    // Class templates
    CLASS_TEMPLATE_NOT_FOUND,
    CLASS_TEMPLATE_NAME_CONFLICT,
    CLASS_TEMPLATE_HAS_INSTANCES,
    CLASS_INSTANCE_NOT_FOUND,

    // Scheduler / schedule views
    INVALID_SCHEDULE_VIEW,
    INVALID_ANCHOR_DATE,
    INVALID_TIME_ZONE,
    IMPORT_FORMAT_INVALID,
    IMPORT_FILE_TOO_LARGE,

    // Images
    IMAGE_REQUIRED,
    INVALID_IMAGE_FORMAT,
    IMAGE_TOO_LARGE,
    IMAGE_NOT_FOUND,

    // Membership requirement
    MEMBERSHIP_REQUIRED,

    // Personal Training Bookings
    PT_LEAD_TIME_VIOLATION,
    PT_TRAINER_OVERLAP,
    PT_TRAINER_CLASS_OVERLAP,
    PT_OUTSIDE_GYM_HOURS,
    PT_BOOKING_NOT_FOUND,
    PT_BOOKING_NOT_ACTIVE,

    // Onboarding
    ONBOARDING_NOT_COMPLETE,

    // Catch-all
    INTERNAL_ERROR,
}
